### ISSUE TITLE
Sugerencia Manual de programación

### ISSUE THREAD

**Issue by aobradors** [msxvr/documentation#32]
En la página 17, nota al pie de página, donde se hace referencia al nombre MSX, se podría añadir el nombre completo de las siglas MSX, donde si no me equivoco, Jordi Orte explica en el iVoox 3x19 que es "Microsoft Extended Basic", así la gente no se preguntará qué significan las siglas.
Un saludo y ánimos por el gran trabajo!!!

**Comment by msxvr** [comment]
Realmente Jordi Orte deja entrever que no solo se usaron esas siglas y que el significado de las mismas variaban en función de a quien se le vendía el concepto. Creo que este libro no es el sitio oportuno como para mojarse con esa definición. Eso mejor se lo dejamos al futuro libro de Jordi ... en cualquier caso, gracias por el apunte.
